# Generated by Django 4.2.7 on 2025-10-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_date',
        ),
        migrations.AlterModelTable(
            name='image',
            table='home_images',
        ),
    ]
